Reset the Error Message: Create Dictionary form
openmrs/openmrs-ocl-client pull request #635
Opened 2020-10-22 18:52 UTC by jwnasambu

# JIRA TICKET NAME:
https://issues.openmrs.org/browse/OCLOMRS-892

# Summary:
I added a react hook to reset the form state when you recreate a form.

2020-10-22 19:34 UTC, ibacher requested changes

2020-10-22 19:34 UTC, ibacher commented on src/apps/dictionaries/pages/CreateDictionaryPage.tsx
> +  resetCreateDictionaryAction: () => void;
```suggestion
  resetCreateDictionary: () => void;
```

2020-10-22 19:34 UTC, ibacher commented on src/apps/dictionaries/pages/CreateDictionaryPage.tsx
> +  resetCreateDictionaryAction: () => void;
The name in the `Props` interface needs to match the name on line 39 and the name in `mapActionsToProps`.

2020-10-22 19:34 UTC, ibacher commented on src/apps/dictionaries/pages/EditDictionaryPage.tsx
> +  useEffect(() => resetEditDictionary, []);
`resetEditDictionary` also needs to be added to `ActionProps` and the start of the `EditDictionaryPage` function.

2020-10-22 21:59 UTC, ibacher commented on src/apps/dictionaries/pages/CreateDictionaryPage.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-dep
```suggestion
  // eslint-disable-next-line react-hooks/exhaustive-deps
```

Linter rule names are very specific!

2020-10-23 11:20 UTC, jwnasambu commented
@ibacher Thanks so for much for reviewing my work.

2020-10-27 13:42 UTC, ibacher approved these changes

2020-10-27 13:44 UTC, merged