OCLOMRS-958::Errors from the backend should marked the field that caused the error
openmrs/openmrs-ocl-client pull request #686
Opened 2021-04-13 16:48 UTC by jwnasambu

# JIRA TICKET NAME:
[:Errors from the backend should marked the field that caused the error](https://issues.openmrs.org/browse/<958>)

# Summary:

2021-04-18 12:53 UTC, hadijahkyampeire commented
@jwnasambu why did you change this PR to a draft? what's up with it?

2021-04-18 18:37 UTC, jwnasambu commented
@dkayiwa, @ibacher  Kindly how do I solve this persistent error `ERROR: Service 'solr' failed to build: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

The command "bash ./start_local_instance.sh" exited with 1. ` causing the travis failure?

2021-04-18 19:16 UTC, jwnasambu commented
@dkayiwa thanks for the help. @hadijahkyampeire the ticket is not complete that is why its in `draft` state

2021-04-18 20:31 UTC, dkayiwa commented
@jwnasambu is the pull rate limit error still a problem?

2021-04-18 20:46 UTC, jwnasambu commented
@dkayiwa Am still fixing the issue but I will gladly communicate once I have pushed the changes. Thanks for asking.

2021-04-18 21:09 UTC, dkayiwa commented
@jwnasambu the issue of pull rate limit?

2021-04-19 07:05 UTC, jwnasambu commented
@dkayiwa after you restarted the server, the issue of pull rate limit cease to be a problem for now. Thanks

2021-04-21 13:02 UTC, ibacher commented
@jwnasambu This looks good so far. Can you rebase your branch on the current `master` (which should fix the test failures). The last thing this PR needs is this (from the ticket):

> 3. We should update the form so that anything in the new error object `__details__` field gets displayed at the bottom of the form, where errors from the backend are displayed today.

2021-05-04 16:55 UTC, ibacher requested changes

2021-05-04 16:55 UTC, ibacher commented on src/redux/utils.ts
> +  errorMsgResponse[key] =
This line should be moved before line 118.

2021-05-04 16:55 UTC, ibacher commented on src/redux/utils.ts
> +    : response.data[key];
```suggestion
```

2021-05-04 16:55 UTC, ibacher commented on src/redux/utils.ts
> +        errorMsgResponse["__detail__"] = response.data.detail,
This line should be outside the for loop.

2021-05-04 16:55 UTC, ibacher commented on src/redux/utils.ts
> +        errorMsgResponse["__detail__"] = response.data.detail,
Also, we should probably get rid of the `if`...`else` altogether. Maybe something like:

```ts
if (response.data && Object.prototype.hasOwnProperty.call(response.data, "detail")) { 
  errorMsgResponse["__detail__"] = response.data.detail;
}

for (let key in response.data) {
  if (key === "__detail__") continue;
  errorMsgResponse[key] =
    // code goes here
}
```

2021-05-04 16:55 UTC, ibacher commented on src/redux/utils.ts
> +        errorMsgResponse["__detail__"] = response.data.detail,
We should also change the type of `errorMsgResponse` to:

```ts
const errorMsgResponse: {[key: string]: string};
```

2021-05-04 19:03 UTC, ibacher commented on src/redux/utils.ts
>    let errorMsgResponse: string[] = [];
```suggestion
```

2021-05-04 19:03 UTC, ibacher commented on src/redux/utils.ts
> +  const errorMsgResponse: {[key: string]: string} = {}; = "Action could not be completed. Please retry.";
```suggestion
  const errorMsgResponse: {[key: string]: string} = {
    "__detail__": "Action could not be completed. Please retry."
  };
```

2021-05-04 19:03 UTC, ibacher commented on src/redux/utils.ts
> +      // code goes here
This comment was meant as a place holder for something like:

```ts
Array.isArray(response.data[key])
 ? response.data[key].join(",")
 : response.data[key]
```

2021-05-05 20:54 UTC, jwnasambu commented
@ibacher locally the changes build successfully but when I try to rebase everything flops and am forced to begin a fresh.  Is it okay for me to close this branch and begin a fresh?

2021-05-05 21:00 UTC, closed without merging